name: Metrics
on:
  schedule: [{cron: "0 0,12 * * *"}]
  push: {branches: ["profile"]}
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: gen metrics
        uses: lowlighter/metrics@latest
        with:
          base: header, activity, community
          token: ${{ secrets.TOKEN }}
          filename: metrics-img.svg
          config_timezone: America/Iqaluit
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          commits_authoring: David Seguin, dseguin, davidseguin@live.ca
          repositories_affiliations: owner, collaborator, organization_member
          repositories_skipped: dseguin, dseguin.github.io, dseguin/Cataclysm-DDA
          plugin_languages: yes
          plugin_languages_ignored: html, css, shell, gnuplot, makefile, batchfile, cmake
          plugin_languages_details: bytes-size, percentage
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes
          plugin_activity: yes
          plugin_activity_filter: push, issue, pr, ref/create, release, review
          plugin_notable: yes
          plugin_introduction: yes
          plugin_introduction_title: no
